# -*- coding: utf-8 -*-
"""Cat_Dog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZ3xVjpOJoQglXkVPOL4gf079H12umFD
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from keras.layers import Dense , Conv2D , MaxPooling2D , Flatten, BatchNormalization, Dropout

from google.colab import drive

drive.mount('/content/drive')

dataset_path = "/content/drive/MyDrive/cat vs dog"

import os

print(os.listdir(dataset_path))

import os
import kagglehub

# Download and define the path to the dataset
path = kagglehub.dataset_download("salader/dogsvscats")

train_dir = os.path.join(path, 'train')
validation_dir = os.path.join(path, 'test')

train_ds = keras.utils.image_dataset_from_directory(
    directory = train_dir,
    labels = "inferred",
    label_mode = "int",
    batch_size = 32,
    image_size = (256,256)
)

validation_ds = keras.utils.image_dataset_from_directory(
    directory = validation_dir,
    labels = "inferred",
    label_mode = "int",
    batch_size = 32,
    image_size = (256,256)
)

#normalize data all values will come in 0-1
def process(image,label):
  image = tf.cast(image/255. ,tf.float32)
  return image,label

train_ds = train_ds.map(process)
validation_ds = validation_ds.map(process)

#create cnn model

model = Sequential()

#layer1
model.add(Conv2D(32,kernel_size=(3,3),padding='valid',activation='relu',input_shape=(256,256,3  )))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

#layer2
model.add(Conv2D(64,kernel_size=(3,3),padding='valid',activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

#layer3
model.add(Conv2D(128,kernel_size=(3,3),padding='valid',activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

#layer4
model.add(Flatten())

#------------------------------ ANN ------------------------
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.1))

#output
model.add(Dense(1,activation='sigmoid'))

model.summary()

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

history = model.fit(train_ds, epochs=10, validation_data=validation_ds)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'] , label='train accuracy')
plt.plot(history.history['val_accuracy'] , label='validation accuracy')
plt.legend()
plt.show()

plt.plot(history.history['accuracy'] , label='train loss')
plt.plot(history.history['val_loss'] , label='validation loss')
plt.legend()
plt.show()

"""# **to do prediction**"""

import cv2

test_img = cv2.imread('/content/Screenshot 2026-10-05 at 2.42.46 AM.png')

plt.imshow(test_img)

test_img.shape

test_img = cv2.resize(test_img,(256,256))

test_input = test_img.reshape((1,256,256,3))

model.predict(test_input)